name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: |
          npm run build
          
          # Crear directorio de salida
          mkdir -p out
          
          # Copiar archivos generados por Next.js
          cp -r .next/standalone/. out/
          
          # Asegurarse de que los directorios necesarios existan
          mkdir -p out/.next/static
          
          # Copiar archivos estáticos
          cp -r .next/static/* out/.next/static/
          cp -r public/* out/
          
          # Crear archivo CNAME
          echo "iansilva2305.github.io/almures-website" > out/CNAME
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'out'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
